---
title: "SFBay Rocky Shore Study Site Map"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Karina J. Nielsen"
date: "Last compiled on `r format(Sys.time(), '%d %B %Y')`"
output:
   bookdown::html_document2: default
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "left",
  fig.width = 7,
  fig.height = 7,
  dev = "png",
  cache = TRUE
)

# echo = FALSE means code will not print, by default
# cache = TRUE saves output results of all chunks so that they do not need to be rerun

```

```{r library, include=FALSE}
library("easypackages")
my_packages <- c("renv", "easypackages",  "here", "ggthemes", "gridExtra", "tidyverse", "lubridate", "patchwork", "tinytex", "bookdown", "ggpubr", "wesanderson", "pals", "ggridges", "hrbrthemes", "viridis", "ggrepel", "data.table", "ggmap")
libraries(my_packages)

# Install packages if needed
#install.packages("easypacakges")
# packages(my_packages) 

# checks to make sure the packages needed are loaded and asks before installing to confirm install in the console window
# Install the relevant libraries - do this one time

```

```{r renv, include=FALSE}
#Track/maintain package versions in workflow

# renv::init # to initialize a new project-local environment with a private R library
# run as needed later in the project to capture required package versions

renv::snapshot() 

# NB must respond and affirm actions in console or you will see the spinning wheel....
# reference for renv workflow: https://rstudio.github.io/renv/articles/renv.html

```

```{r functions, include=FALSE}

#As needed...

```

```{r here, include=FALSE}

## Confirm working directory for project
here::here() # use this to work with sub-directories less awkwardly and share projects across users/machines more easily.
```

```{r map-notes, include = FALSE}
# following tutorial here: https://www.littlemissdata.com/blog/maps

#  API key created // Use this key in your application by passing it with the key=API_KEY parameter
```

```{r set API key,include = FALSE}

#Set your API Key # use console to keep API key private # key in text file
#ggmap::register_google(key = "KEY_HERE")
```

```{r read in data files, include = FALSE}
sites <- read_csv(here::here ("data","sfbay_rockweed_site_names_locations.csv"), col_names = TRUE)
rtcsites <- sites[ which(sites$group=='rtc'), ]
pspsites <- sites[ which(sites$group=='psp'), ]
tibsites <- sites[ which(sites$group2=='tib'), ]
ggbsites <- sites[ which(sites$group2=='ggb'), ]
```


```{r site-maps, fig.cap = "Map of study sites in central and northern San Francsico Bay.", fig.width = 7, fig.height = 7, message=FALSE}

# Create a map with all of the sites plotted.

all <-
  ggmap(
    get_map(
      location = c(lon = -122.43448569306662, lat = 37.88189695628280),
      source = "google",
      zoom = 11,
      scale = 2 ,
      size = c(640, 640),
      format = "png8",
      maptype = 'satellite',
      color = 'color'
    )
  )

all2 <- all + geom_point(aes(x = long, y = lat),
                 data = sites,
                 size = 2,
                 shape = 21,
                 color = 'light blue',
                 stroke = 1) +
    theme(legend.position = "none")

all2

# Create a map with all of the sites plotted and coded by site type.

all3 <- all + geom_point(aes(x = long, y = lat, color = site_type),
                 data = sites,
                 size = 3,
                 shape = 21,
                 stroke = 1) +
    theme(legend.position = "bottom")+
  guides(col = guide_legend(ncol = 3))
  
```

```{r map-all save, include=FALSE}
all2
ggsave("all2.pdf", width = 7.5, height = 10, units = "in")
```

```{r map-all-type save, include=FALSE}
all3
ggsave("all3.pdf", width = 7.5, height = 10, units = "in")
```

```{r rtc-map, message=FALSE, warning=FALSE, fig.cap= " Reference sites used to inform restoration planning and design.", fig.width = 7, fig.height = 7}
# Create a map zoomed in for RTC ref sites .

rtc <-
  ggmap(
    get_map(
      location = c(lon = -122.47121817785745, lat = 37.91352394528543),
      source = "google",
      zoom = 13,
      scale = 2 ,
      size = c(640, 640),
      format = "png8",
      maptype = 'satellite',
      color = 'color'
    )
  )

rtc2 <- rtc + geom_point(aes(x = long, y = lat, color = site_type),
                 data = rtcsites,
                 size = 3,
                 shape = 21,
                 stroke = 1) +
    theme(legend.position = "bottom")+
  guides(col = guide_legend(nrow = 1))+
  geom_label_repel(
    aes(x = long, y = lat, label = site_name),
    data = rtcsites,
    size = 2,
    box.padding = 0.2,
    point.padding = 0.3,
    segment.color = 'black'
  )

rtc2
```

```{r rtc-map save, include=FALSE}
rtc2
ggsave("rtc2.pdf", width = 7.5, height = 10, units = "in")
```


```{r tib-map, message=FALSE, warning=FALSE, fig.cap= "Map of central San Francsicso Bay study sites by type in region 2.", , fig.width = 7, fig.height = 7}
# Create a map zoomed in for Tiburon sites .

options(ggrepel.max.overlaps = Inf)
tib <-
  ggmap(
    get_map(
      location = c(lon = -122.47121817785745, lat = 37.91352394528543),
      source = "google",
      zoom = 12,
      scale = 2 ,
      size = c(640, 640),
      format = "png8",
      maptype = 'satellite',
      color = 'color'
    )
  )

tib2 <- tib + geom_point(aes(x = long, y = lat, color = site_type),
                 data = tibsites,
                 size = 3,
                 shape = 21,
                 stroke = 1) +
    theme(legend.position = "bottom")+
  guides(col = guide_legend(nrow = 1))+
  geom_label_repel(
    aes(x = long, y = lat, label = site_name),
    data = tibsites,
    size = 2,
    box.padding = 0.2,
    point.padding = 0.3,
    segment.color = 'black'
  )

tib2

```

```{r tib-map save, include=FALSE}
tib2
ggsave("tib2.pdf", width = 7.5, height = 10, units = "in")
```


```{r psp-map, message=FALSE, warning=FALSE, fig.cap= "Map of central San Francsicso Bay study sites by type in region 3.", , fig.width = 7, fig.height = 7}
# Create a map zoomed in for pt san pedro sites

psp <-
  ggmap(
    get_map(
      location = c(lon = -122.39946372242072, lat = 37.940875791830365),
      source = "google",
      zoom = 13,
      scale = 2 ,
      size = c(640, 640),
      format = "png8",
      maptype = 'satellite',
      color = 'color'
    )
  )

psp2 <- psp + geom_point(aes(x = long, y = lat, color = site_type),
                 data = pspsites,
                 size = 3,
                 shape = 21,
                 stroke = 1) +
    theme(legend.position = "bottom")+
  guides(col = guide_legend(nrow = 1))+
  geom_label_repel(
    aes(x = long, y = lat, label = site_name),
    data = pspsites,
    size = 2,
    box.padding = 0.2,
    point.padding = 0.3,
    segment.color = 'black'
  )

psp2

```

```{r psp-map save, include=FALSE}
psp2
ggsave("psp2.pdf", width = 7.5, height = 10, units = "in")
```

```{r ggb-map, message=FALSE, warning=FALSE, fig.cap = "Map of central San Francsicso Bay study sites by type in region 1.", fig.width = 7, fig.height = 7}
# Create a map zoomed in for gate + richardson bay sites

ggb <-
  ggmap(
    get_map(
      location = c(lon = -122.47499472820377, lat = 37.84184640221922),  
      source = "google",
      zoom = 12,
      scale = 2 ,
      size = c(640, 640),
      format = "png8",
      maptype = 'satellite',
      color = 'color'
    )
  )

ggb2 <- ggb + geom_point(aes(x = long, y = lat, color = site_type),
                 data = ggbsites,
                 size = 3,
                 shape = 21,
                 stroke = 1) +
    theme(legend.position = "bottom")+
  guides(col = guide_legend(nrow = 1))+
  geom_label_repel(
    aes(x = long, y = lat, label = site_name),
    data = ggbsites,
    size = 2,
    box.padding = 0.2,
    point.padding = 0.3,
    segment.color = 'black'
  )

ggb2

```
```{r ggb-map save, include=FALSE}
ggb2
ggsave("ggb2.pdf", width = 7.5, height = 10, units = "in")
```





